version: '3.8'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: test-mongo
    restart: always
    logging:
      options:
        max-size: 4g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=work
      - MONGO_INITDB_ROOT_PASSWORD=work
    image: mongo
  postgres_db:
    image: postgres:latest
    container_name: PostgresDB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'work'
      MYSQL_PASSWORD: 'work'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  postgres_db:
   driver: local
  mysql_db:
    driver: local